services:
  # ========== FLASK APP ==========
  web:
    image: mananurrehman/finvestigate:latest
    container_name: finvestigate-web
    ports:
      - "5002:5000"
    env_file:
      - .env.production
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - finvestigate-network

  # ========== POSTGRESQL ==========
  db:
    image: postgres:15-alpine
    container_name: finvestigate-db
    env_file:
      - .env.production
    # ports:
      # - "5432:5432"
      # no need to expose as it is already in use on the same server by another service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - finvestigate-network

# ========== PERSISTENT VOLUMES ==========
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ubuntu/finvestigate-data/postgres
  
# ========== NETWORK ==========
networks:
  finvestigate-network:
    driver: bridge